export const ACTION_TYPE = {
  SHOW_AND_HIDE_MEGA_MENU: 'SHOW_AND_HIDE_MEGA_MENU',
  SET_PRODUCTS: 'SET_PRODUCTS',
  WISH_LIST_PRODUCTS: 'WISH-LIST_PRODUCTS',
  CLOSE_MODEL_WINDOW: 'CLOSE_MODEL_WINDOW',
  SELECTED_PRODUCTS: 'SELECTED_PRODUCTS',
  SHOW_SIDE_BAR: 'SHOW_SIDE_BAR',
};
