export const ACTION_TYPE = {
  SHOW_AND_HIDE_MEGA_MENU: 'SHOW_AND_HIDE_MEGA_MENU',
  SET_PRODUCTS: 'SET_PRODUCTS',
  ADD_TO_CARD_PRODUCTS: 'ADD_TO_CARD_PRODUCTS',
  CLOSE_MODEL_WINDOW: 'CLOSE_MODEL_WINDOW',
  SELECTED_PRODUCTS: 'SELECTED_PRODUCTS',
  SHOW_SIDE_BAR: 'SHOW_SIDE_BAR',
  SET_EMAIL_ADDRESS: 'SET_EMAIL_ADDRESS',
  WISH_LIST_PRODUCTS: 'WISH_LIST_PRODUCTS',
  SHOP_PRODUCT_PREV: 'SHOW_PRODUCT_PREV',
  SHOP_PRODUCT_PREV_DATA: 'SHOW_PRODUCT_PREV_DATA',
};
